name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
      - '.github/**'

jobs:

  test:
    strategy:
      matrix:
        node-version: [ 21.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # - name: Setup Node ${{ matrix.node-version }}
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: ${{ matrix.node-version }}

    # - name: Cache
    #   id: cache-modules
    #   uses: actions/cache@v3
    #   with:
    #     path: node_modules
    #     key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

    # - name: Install
    #   if: steps.cache-modules.outputs.cache-hit != 'true'
    #   run: npm install

    # - name: Test
    #   run: npm test

  deploy:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: [ test ]
    runs-on: ubuntu-latest
    env:
      registry: ghcr.io
      image: ${{ github.repository }}
    permissions:
      packages: write
      contents: read
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Main Image
      run: |
        echo "SHA=${{ github.sha }}"
        docker build \
          --build-arg "SHA=${{ github.sha }}" \
          --label "SHA=${{ github.sha }}" \
          --tag ${{ env.registry }}/${{ env.image }}:commit-${{ github.sha }} \
          --tag ${{ env.registry }}/${{ env.image }}:latest \
          .

    - name: Inspect Images
      run: |
        docker inspect ${{ env.registry }}/${{ env.image }}:latest

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Images to Registry
      run: |
        docker push ${{ env.registry }}/${{ env.image }}:commit-${{ github.sha }}
        docker push ${{ env.registry }}/${{ env.image }}:latest
